name: Pull latest

on:
  workflow_dispatch:
    inputs:
      upstream-remote-branch:
        required: true
        type: string
        description: The branch on the upstream remote that should be fetch
      upstream-local-branch:
        required: true
        type: string
        description: The branch on the local repo that should be merged with the upstream remote branch
      upstream-remote:
        required: true
        type: string
        description: The HTTPS format remote URL of the upstream, e.g., https://github.com/DataDog/helm-charts.git

jobs:
  pull-latest:
    name: Pull Latest From Upstream Remote
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Local
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{ inputs.upstream-local-branch }}
      - name: Add Remote
        run: |
          git remote add upstream ${{ inputs.upstream-remote }}
      - name: Setup Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Pull and Merge into Local
        run: |
          git fetch upstream ${{ inputs.upstream-remote-branch }}
          git merge upstream/${{ inputs.upstream-remote-branch }}
      - name: Push to Origin
        run: |
          git push origin ${{ inputs.upstream-local-branch }}
